# github workflow to run tests

name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - run: |
            sudo apt update
            sudo apt install -y unzip nodejs npm
            sudo snap install rustup --classic
            rustup update
            cd tools
            npm install
            cd ..
            chmod +x tools/run
            tools/run test
